# Generated by Django 4.0.2 on 2023-03-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('completed', models.BooleanField()),
                ('tags', models.ManyToManyField(related_name='tags', to='todo_list_application.Tag')),
            ],
            options={
                'ordering': ['completed'],
            },
        ),
    ]
